site_name: DNSDig Docs Site
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - DNSDig API: dnsdig-api.md
  - DNSDigd: dnsdigd.md
theme:
  name: material
  icon:
    logo: material/dns-outline
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
repo_url: https://github.com/tistaharahap/dnsdig
repo_name: tistaharahap/dnsdig
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tistaharahap
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tista
    - icon: fontawesome/solid/blog
      link: https://bango29.com
  generator: false
  homepage: https://tistaharahap.github.io/dnsdig
copyright: Made with 💚️ by <a href="https://twitter.com/tista" target="_blank">Tista</a>
