name: DNS Dig CI

on:
  push:
    paths:
      - dnsdig/**
      - tests/**
      - .github/dnsdig-api.yaml

env:
  PYTEST_INI: pytest-ci.ini

jobs:
  build:
    name: Test DNS Dig API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        python-version: ['3.11']
        mongodb-version: ['6.0']
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Black Check
        uses: jpetrucciani/black-check@master
        with:
          path: './dnsdig -t py311'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: supercharge
          mongodb-password: secret
          mongodb-db: supercharge
      - name: Install Dependencies
        run: |
          python3 -m pip install poetry==1.3.2
          python3 -m poetry config virtualenvs.create false
          python3 -m poetry install
      - name: Run Tests
        run: pytest -x -vv -c pytest-ci.ini --cov=dnsdig --cov-report=xml --cov-fail-under=70 tests
